# Generated by Django 4.1.5 on 2023-04-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Posts.comments'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Posts/User/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
