# Generated by Django 4.1.5 on 2023-04-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_remove_blogpost_likes_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Posts.blogpost'),
        ),
    ]
