# Generated by Django 4.1.5 on 2023-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Admin/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Student/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Teacher/profile_pics/'),
        ),
    ]
