# Generated by Django 4.1.5 on 2023-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_adminprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='User/Profile/images'),
        ),
    ]
