# Generated by Django 4.1.5 on 2023-04-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collegename', to='Account.adminuser')),
                ('teacher', models.ManyToManyField(related_name='teacherenrolled', to='Account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collegeadmin', to='Account.adminuser')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facultyprovides', to='Account.faculty')),
                ('students', models.ManyToManyField(related_name='studentenrolled', to='Account.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(related_name='course_for', to='Account.courses')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaches_subject', to='Account.teacher')),
            ],
        ),
    ]
