# Generated by Django 4.1.5 on 2023-04-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=500)),
                ('descripton', models.TextField()),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('date_line', models.DateTimeField()),
                ('assigned_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_given', to='Account.teacher')),
                ('assigned_to', models.ManyToManyField(related_name='assignment_recevied', to='Account.student')),
                ('sems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.semester')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.courses')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(max_length=1000, upload_to='Assignemnt/')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='Assignements.createassignment')),
                ('submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_by', to='Account.student')),
                ('submited_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submited_to', to='Account.teacher')),
            ],
        ),
    ]
