# Generated by Django 4.1.5 on 2023-04-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_adminprofile_profile_pic_and_more'),
        ('Assignements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(max_length=1000, upload_to='Assignemnt/')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='Assignements.createassignment')),
                ('submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_by', to='Account.student')),
                ('submited_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submited_to', to='Account.teacher')),
            ],
        ),
    ]
